CREATE DATABASE KruzeAutoDB;
GO

USE KruzeAutoDB;

CREATE TABLE [Users](
	[UserID] uniqueidentifier NOT NULL,
	[Email] nvarchar(50) NOT NULL,
	[UserName] nvarchar(50) NOT NULL,
	[Password] nvarchar(50) NOT NULL,
	[Country] nvarchar(50) NOT NULL,
	[County] nvarchar(50) NOT NULL,
	[City] nvarchar(50) NOT NULL,
	[PhoneNumber] nvarchar(50) NOT NULL,
	[CreationDate] date NOT NULL,
	[Subscribed] nvarchar(3) NOT NULL,
CONSTRAINT [PK_Users] PRIMARY KEY ([UserID]));

CREATE TABLE [MesageImbox](
	[UserID] uniqueidentifier NOT NULL,
	[UserIDDestination] uniqueidentifier NOT NULL,
	[MesageID] uniqueidentifier NOT NULL,
	[CreationDate] date NOT NULL,
	[Read] nvarchar(3),
	[MesageContent] text NOT NULL,
CONSTRAINT [PK_MesageImbox] PRIMARY KEY ([MesageID]),
CONSTRAINT [FK_MesageImbox_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [CarsAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[Kilometer] int,
	[FabricationYear] int NOT NULL,
	[VIN] nvarchar(50),
	[FuelType] nvarchar(25) NOT NULL,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[Color] nvarchar(15),
	[ColorType] nvarchar(15),
	[Power] int,
	[Transmission] nvarchar(25),
	[CubicCapacity] int,
	[EmissionClass] nvarchar(15),
	[ManualClimatisation] nvarchar(3),
	[AutomaticAirConditioning] nvarchar(3),
	[Bluetooth] nvarchar(3),
	[CDPlayer] nvarchar(3),
	[CentralLocking]nvarchar(3),
	[CruiseControl] nvarchar(3),
	[ElectricHeatedSeats] nvarchar(3),
	[ElectricSeatAdjustment] nvarchar(3),
	[ElectricSideMirror] nvarchar(3),
	[ElectricWindows] nvarchar(3),
	[MP3Interface] nvarchar(3),
	[MultifunctionSteeringWheel] nvarchar(3),
	[NavigationSystem] nvarchar(3),
	[OnBoardComputer] nvarchar(3),
	[PowerAssistedSteering] nvarchar(3),
	[RainSensor] nvarchar(3),
	[StartStopSystem] nvarchar(3),
	[Sunroof] nvarchar(3),
	[TunerAudio] nvarchar(3),
	[VentilatedSeats] nvarchar(3),
	[ABS] nvarchar(3),
	[ESP] nvarchar(3),
	[AdaptiveCruiseControl] nvarchar(3),
	[AdaptiveLighting] nvarchar(3),
	[BlindSpotMonitor] nvarchar(3),
	[CollisionAvoidanceSystem] nvarchar(3),
	[DaytimeRunningLights] nvarchar(3),
	[FogLamp] nvarchar(3),
	[4x4] nvarchar(3),
	[KeylessEntry] nvarchar(3),
	[LaneDepartueWarningSystem] nvarchar(3),
	[LEDHeadlights] nvarchar(3),
	[LightSensor] nvarchar(3),
	[TractionControl] nvarchar(3),
	[XenonHeadlights] nvarchar(3),
	[FrontParkingSensor] nvarchar(3),
	[RearParkingSensor] nvarchar(3),
	[RearCamera] nvarchar(3),
	[SelfSteeringSystem] nvarchar(3),
	[FullLeatherSeats] nvarchar(3),
	[SportSeats] nvarchar(3),
	[AlcantaraSeats] nvarchar(3),
	[Description] text,
CONSTRAINT [PK_CarsAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_CarsAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [MotorcyclesAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[Kilometer] int,
	[FabricationYear] int NOT NULL,
	[FuelType] nvarchar(25) NOT NULL,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[Color] nvarchar(15),
	[ColorType] nvarchar(15),
	[Power] int,
	[Transmission] nvarchar(25),
	[CubicCapacity] int,
	[DrivingMode] nvarchar(25),
	[ABS] nvarchar(3),
	[Box] nvarchar(3),
	[CatalyticConverter] nvarchar(3),
	[ElectricStarter] nvarchar(3),
	[Kickstarter] nvarchar(3),
	[RollOverBar] nvarchar(3),
	[Windshield] nvarchar(3),
	[Description] text,
CONSTRAINT [PK_MotorcyclesAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_MotorcyclesAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [VansAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[Kilometer] int,
	[FabricationYear] int NOT NULL,
	[FuelType] nvarchar(25) NOT NULL,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[Color] nvarchar(15),
	[ColorType] nvarchar(15),
	[Power] int,
	[Transmission] nvarchar(25),
	[CubicCapacity] int,
	[EmissionClass] nvarchar(15),
	[NumberOfSeats] int,
	[Crane] nvarchar(3),
	[SilidingDoor] nvarchar(3),
	[TailLift] nvarchar(3),
	[TrailerCoupling] nvarchar(3),
	[ManualClimatisation] nvarchar(3),
	[AutomaticAirConditioning] nvarchar(3),
	[Bluetooth] nvarchar(3),
	[CDPlayer] nvarchar(3),
	[CentralLocking]nvarchar(3),
	[CruiseControl] nvarchar(3),
	[ElectricHeatedSeats] nvarchar(3),
	[ElectricSeatAdjustment] nvarchar(3),
	[ElectricSideMirror] nvarchar(3),
	[ElectricWindows] nvarchar(3),
	[MP3Interface] nvarchar(3),
	[MultifunctionSteeringWheel] nvarchar(3),
	[NavigationSystem] nvarchar(3),
	[OnBoardComputer] nvarchar(3),
	[PowerAssistedSteering] nvarchar(3),
	[RainSensor] nvarchar(3),
	[StartStopSystem] nvarchar(3),
	[Sunroof] nvarchar(3),
	[TunerAudio] nvarchar(3),
	[VentilatedSeats] nvarchar(3),
	[ABS] nvarchar(3),
	[ESP] nvarchar(3),
	[AdaptiveCruiseControl] nvarchar(3),
	[AdaptiveLighting] nvarchar(3),
	[BlindSpotMonitor] nvarchar(3),
	[CollisionAvoidanceSystem] nvarchar(3),
	[DaytimeRunningLights] nvarchar(3),
	[FogLamp] nvarchar(3),
	[WheelFormula] nvarchar(3),
	[KeylessEntry] nvarchar(3),
	[LaneDepartueWarningSystem] nvarchar(3),
	[LEDHeadlights] nvarchar(3),
	[LightSensor] nvarchar(3),
	[TractionControl] nvarchar(3),
	[XenonHeadlights] nvarchar(3),
	[FrontParkingSensor] nvarchar(3),
	[RearParkingSensor] nvarchar(3),
	[RearCamera] nvarchar(3),
	[SelfSteeringSystem] nvarchar(3),
	[FullLeatherSeats] nvarchar(3),
	[SportSeats] nvarchar(3),
	[AlcantaraSeats] nvarchar(3),
	[GVW] int,
	[Description] text,
CONSTRAINT [PK_VansAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_VansAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [TrucksAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[Kilometer] int,
	[FabricationYear] int NOT NULL,
	[FuelType] nvarchar(25) NOT NULL,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[Color] nvarchar(15),
	[ColorType] nvarchar(15),
	[Power] int,
	[Transmission] nvarchar(25),
	[CubicCapacity] int,
	[EmissionClass] nvarchar(15),
	[AlloyWheels] nvarchar(3),
	[Compressor] nvarchar(3),
	[Crane] nvarchar(3),
	[TailLift] nvarchar(3),
	[TrailerCoupling] nvarchar(3),
	[ManualClimatisation] nvarchar(3),
	[AutomaticAirConditioning] nvarchar(3),
	[Axles2] nvarchar(3),
	[Axles3] nvarchar(3),
	[AxlesMore] nvarchar(3),
	[WhellFormula] nvarchar(3),
	[RetarderIntarder] nvarchar(3),
	[SecondaryAirConditioning]nvarchar(3),
	[Abs] nvarchar(3),
	[EBS] nvarchar(3),
	[ESP] nvarchar(3),
	[ParticulateFilter] nvarchar(3),
	[GVW] int,
	[Description] text,
CONSTRAINT [PK_TrucksAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_TrucksAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [TrailersAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[FabricationYear] int NOT NULL,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[AirSuspension] nvarchar(3),
	[Crane] nvarchar(3),
	[DiscBrake] nvarchar(3),
	[TailLift] nvarchar(3),
	[Axles2] nvarchar(3),
	[Axles3] nvarchar(3),
	[AxlesMore] nvarchar(3),
	[GVW] int,
	[LoadCapacity] int,
	[ABS] nvarchar(3),
	[ESP] nvarchar(3),
	[Description] text,
CONSTRAINT [PK_TrailersAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_TrailersAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [SemiTrailersAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[FabricationYear] int NOT NULL,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[AirSuspension] nvarchar(3),
	[DiscBrake] nvarchar(3),
	[Axles2] nvarchar(3),
	[Axles3] nvarchar(3),
	[AxlesMore] nvarchar(3),
	[GVW] int,
	[LoadCapacity] int,
	[ABS] nvarchar(3),
	[ESP] nvarchar(3),
	[Description] text,
CONSTRAINT [PK_SemiTrailersAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_SemiTrailersAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [BusesAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[Kilometer] int,
	[FabricationYear] int NOT NULL,
	[FuelType] nvarchar(25) NOT NULL,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[Color] nvarchar(15),
	[ColorType] nvarchar(15),
	[Power] int,
	[Transmission] nvarchar(25),
	[CubicCapacity] int,
	[EmissionClass] nvarchar(15),
	[NumberOfSeats] int,
	[ManualClimatisation] nvarchar(3),
	[AutomaticAirConditioning] nvarchar(3),
	[TrailerCoupling] nvarchar(3),
	[RetarderIntarder] nvarchar(3),
	[SecondaryAirConditioning] nvarchar(3),
	[AuxiliaryHeating] nvarchar(3),
	[ColdStore] nvarchar(3),
	[CruiseControl] nvarchar(3),
	[DriversSleepingCompartment] nvarchar(3),
	[Kichen] nvarchar(3),
	[NavigationSystem] nvarchar(3),
	[SleeperSeats] nvarchar(3),
	[TV] nvarchar(3),
	[WC] nvarchar(3),
	[Abs] nvarchar(3),
	[ESP] nvarchar(3),
	[ParticulateFilter] nvarchar(3),
	[GVW] int,
	[Description] text,
CONSTRAINT [PK_BusesAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_BusesAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [ConstructionMachinesAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[FabricationYear] int NOT NULL,
	[OperatingHours] int,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[EmissionClass] nvarchar(15),
	[BSS] nvarchar(3),
	[CentralLubricantAplic] nvarchar(3),
	[QuickChangeAttachment] nvarchar(3),
	[ABS] nvarchar(3),
	[4x4] nvarchar(3),
	[ParticulateFilter] nvarchar(3),
	[Description] text,
CONSTRAINT [PK_ConstructionMachinesAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_ConstructionMachinesAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [AgriculturalMachinesAnnoucements](
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[UserID] uniqueidentifier NOT NULL,
	[Views] int NOT NULL,
	[Promoted] nvarchar(3),
	[Active] nvarchar(3),
	[CreationDate] date NOT NULL,
	[Update] date,
	[Condition] nvarchar(15) NOT NULL,
	[Title] nvarchar(50) NOT NULL,
	[Brand] nvarchar(50) NOT NULL,
	[Model] nvarchar(50) NOT NULL,
	[Type] nvarchar(50) NOT NULL,
	[FabricationYear] int NOT NULL,
	[OperatingHours] int,
	[Power] int,
	[Price] int NOT NULL,
	[NegociablePrice] nvarchar(3) NOT NULL,
	[Currency] nvarchar(3) NOT NULL,
	[EmissionClass] nvarchar(15),
	[Cabin] nvarchar(3),
	[FrontHydraulics] nvarchar(3),
	[FrontJack] nvarchar(3),
	[ManualClimatisation] nvarchar(3),
	[AutomaticAirConditioning] nvarchar(3),
	[AuxiliaryHeating] nvarchar(3),
	[SecondaryAirConditioning] nvarchar(3),
	[ABS] nvarchar(3),
	[4x4] nvarchar(3),
	[PowerAssistedSteering] nvarchar(3),
	[Description] text,
CONSTRAINT [PK_AgriculturalMachinesAnnoucements] PRIMARY KEY ([AnnoucementsID]),
CONSTRAINT [FK_AgriculturalMachinesAnnoucements_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [UsersPictures](
	[UserID] uniqueidentifier NOT NULL,
	[Image] image,
CONSTRAINT [PK_UsersPictures] PRIMARY KEY ([UserID]),
CONSTRAINT [FK_UsersPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]));

CREATE TABLE [CarsAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_CarsAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_CarsAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_CarsAnnoucementsPictures_CarsAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [CarsAnnoucements]([AnnoucementsID]));

CREATE TABLE [MotorcyclesAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_MotorcyclesAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_MotorcyclesAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_MotorcyclesAnnoucementsPictures_MotorcyclesAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [MotorcyclesAnnoucements]([AnnoucementsID]));

CREATE TABLE [VansAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_VansAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_VansAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_VansAnnoucementsPictures_VansAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [VansAnnoucements]([AnnoucementsID]));

CREATE TABLE [TrucksAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_TrucksAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_TrucksAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_TrucksAnnoucementsPictures_TrucksAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [TrucksAnnoucements]([AnnoucementsID]));

CREATE TABLE [TrailersAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_TrailersAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_TrailersAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_TrailersAnnoucementsPictures_TrailersAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [TrailersAnnoucements]([AnnoucementsID]));

CREATE TABLE [SemiTrailersAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_SemiTrailersAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_SemiTrailersAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_SemiTrailersAnnoucementsPictures_SemiTrailersAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [SemiTrailersAnnoucements]([AnnoucementsID]));

CREATE TABLE [BusesAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_BusesAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_BusesAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_BusesAnnoucementsPictures_BusesAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [BusesAnnoucements]([AnnoucementsID]));

CREATE TABLE [ConstructionMachinesAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_ConstructionMachinesAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_ConstructionMachinesAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_ConstructionMachinesAnnoucementsPictures_ConstructionMachinesAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [ConstructionMachinesAnnoucements]([AnnoucementsID]));

CREATE TABLE [AgriculturalMachinesAnnoucementsPictures](
	[UserID] uniqueidentifier NOT NULL,
	[AnnoucementsID] uniqueidentifier NOT NULL,
	[PictureID] uniqueidentifier NOT NULL,
	[Image] image,
	[Primary] nvarchar(3),
CONSTRAINT [PK_AgriculturalMachinesAnnoucementsPictures] PRIMARY KEY ([PictureID], [AnnoucementsID]),
CONSTRAINT [FK_AgriculturalMachinesAnnoucementsPictures_Users] FOREIGN KEY ([UserID])
	REFERENCES [Users]([UserID]),
CONSTRAINT [FK_AgriculturalMachinesAnnoucementsPictures_AgriculturalMachinesAnnoucements] FOREIGN KEY ([AnnoucementsID])
	REFERENCES [AgriculturalMachinesAnnoucements]([AnnoucementsID]));

